stages:
  - build

build-linux:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libsdl2-dev libgl1-mesa-dev
  script:
    - ./build.sh
  artifacts:
    name: podoae-linux
    paths:
      - podoae

build-windows:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y mingw-w64 wget tar zip
    - wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.3/SDL2-devel-2.30.3-mingw.tar.gz
    - tar -xzf SDL2-devel-2.30.3-mingw.tar.gz
  script:
    - x86_64-w64-mingw32-gcc -Wall -Wextra -IInclude -ISDL2-2.30.3/x86_64-w64-mingw32/include main.c pomodoro.c Include/microui/microui.c Include/renderer/renderer.c -LSDL2-2.30.3/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -lopengl32 -o podoae.exe
    - cp SDL2-2.30.3/x86_64-w64-mingw32/bin/SDL2.dll .
    - zip podoae-windows-x64.zip podoae.exe SDL2.dll README.md
  artifacts:
    name: podoae-windows
    paths:
      - podoae-windows-x64.zip
